/* *****************************************************************************************
                              A list of Odhinn's names
Odin has 170 different names. More if you count the different spellings of the same name:
ODIN -> ODHINN -> OTHEN -> WODEN -> WOTAN
Here I have selected 96 of them.
The first name is Old Norse ---> English spelling 
The Second Name is the Rune friendly Spelling (Y=I, C=K, V=W, etc.)
*******************************************************************************************/

const String cNameList[96][2] = {
  { "Alfadhr", "alfadhr" }, 
  { "Aldagautr", "aldagautr" },
  { "Atridhr", "atridhr" },
  { "Asagrim", "asagrim" },
  { "Audhun", "audhun" },
  { "Baleygr Baleyg", "baleigr baleig" },
  { "Biflindi", "biflindi" },
  { "Blindr", "blindr" },
  { "Bolverkr", "bolwerkr" },
  { "Draugadrottinn", "draugadrottinn" },
  { "Dresvarpr", "dreswarpr" },
  { "Drottinn", "drottinn" },
  { "Farmagnudhr", "farmagnudhr" },
  { "Farmatyr", "farmatir" },
  { "Fimbultyr", "fimbultir" },
  { "Fimbulthulr", "fimbulthulr" },
  { "Fjolnir", "fjolnir" },
  { "Fjolsvidhr", "fjolswidhr" },
  { "Foldardrottinn", "foldardrottinn" },
  { "Forni", "forni" },
  { "Gagnradhr", "gagnradhr" },
  { "Galdrafodhr", "galdrafodhr" },
  { "Fadhir galdrs", "fadhir galdrs" },
  { "Ganglari", "ganglari" },
  { "Gautr", "gautr" },
  { "Geirtyr", "geirtir" },
  { "Geirvaldr", "geirwaldr" },
  { "Glapsvidhr", "glapswidhr" },
  { "Gondlir", "gondlir" },
  { "Grimnir", "grimnir" },
  { "Gunnblindi", "gunnblindi" },
  { "Hagvirkr", "hagwirkr" },
  { "Hangadrottinn", "hangadrottinn" },
  { "Hangatyr", "hangatir" },
  { "Hangi", "hangi" },
  { "Haptagudh", "haptagudh" },
  { "Harbardhr", "harbardhr" },
  { "Harr", "harr" },
  { "Havi", "hawi" },
  { "Helblindi", "helblindi" },
  { "Herjafodhr", "herjafodhr" },
  { "Herjan", "herjan" },
  { "Herteitr", "herteitr" },
  { "Hildolfr", "hildolfr" },
  { "Hjaldrgegnir", "hjaldrgegnir" },
  { "Hjalmberi", "hjalmberi" },
  { "Hnikarr", "hnikarr" },
  { "Hoarr", "hoarr" },
  { "Hrafnagudh", "hrafnagudh" },
  { "Hroptatyr", "hroptatir" },
  { "Jafnharr", "jafnharr" },
  { "Odhinn", "odhinn" },
  { "Ofnir", "ofnir" },
  { "Reidhartyr", "reidhartir" },
  { "Rognir", "rognir" },
  { "Runatyr", "runatir" },
  { "Sadhr", "sadhr" },
  { "Sanngetall", "sanngetall" },
  { "Sidhgrani", "sidhgrani" },
  { "Sidhhottr", "sidhhottr" },
  { "Sidhskeggr", "sidhskeggr" },
  { "Sigfodhr", "sigfodhr" },
  { "Sigrunnr", "sigrunnr" },
  { "Sigtryggr", "sigtriggr" },
  { "Sigtyr", "sigtir" },
  { "Sigthror", "sigthror" },
  { "Skilfingr", "skilfingr" },
  { "Skollvaldr", "skollwaldr" },
  { "Svafnir", "swafnir" },
  { "Sveigdhir", "sweigdhir" },
  { "Svidhrir", "swidhrir" },
  { "Svipall", "swipall" },
  { "Svolnir", "swolnir" },
  { "Tviblindi", "twiblindi" },
  { "Thekkr", "thekkr" },
  { "Thrasarr", "thrasarr" },
  { "Thridhi", "thridhi" },
  { "Thriggi", "thriggi" },
  { "Throttr", "throttr" },
  { "Udhr", "udhr" },
  { "Vafudhr", "wafudhr" },
  { "Valfodhr", "walfodhr" },
  { "Valgautr", "walgautr" },
  { "Valkjosandi", "walkjosandi" },
  { "Valtamr", "waltamr" },
  { "Valtyr", "waltir" },
  { "Valthognir", "walthognir" },
  { "Vegtam", "wegtam" },
  { "Veratyr", "weratir" },
  { "Vidhfrager", "widhfrager" },
  { "Vidhrir", "widhrir" },
  { "Vidhrimnir", "widhrimnir" },
  { "Vidhurr", "widhurr" },
  { "Vingnir", "wingnir" },
  { "Woden", "woden" },
  { "Wotan", "wotan" },
};